version: "3.9"

services:
    app:
        image: test_api:latest
        container_name: test_api
        entrypoint: [
            "uvicorn", "main:app",
            "--host", "0.0.0.0",
            "--port", "8000",
            "--reload"
        ]
#        ports:
#            - "8000:8000"
        restart: unless-stopped